#!/bin/bash
echo Route.put Post-Remove Script Running!
if [ "$1" = remove ]; then
    echo Removing routeput user
    deluser --force routeput
fi
if [ "$1" = purge ]; then
    echo Removing routeput directory
    rm -R /usr/share/routeput/
fi
